spring:
  application:
    name: KafkaAxonExample
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

axon:
  kafka:
    clientid: kafka-axon-example
    #defaulttopic: local.event
    producer:
      retries: 0
      bootstrapservers: localhost:9092
      event-processor-mode: tracking
    consumer:
      bootstrapservers: localhost:9092
      group-id: "local.event.consumer-group"
      event-processor-mode: tracking
    properties:
      security.protocol: PLAINTEXT