#All the configuration is hard-coded in the JAVA code.
spring:
  application:
    name: CardDemo
  main:
    allow-bean-definition-overriding: true

axon:
  kafka:
    bootstrapservers: 127.0.0.1:9092
    producer:
      topic: Topic-1
    consumer: 
      topic: Topic-1
      group-id: Group-1
  mongo:
    host: localhost
    port: 27017
    databse: db-axon0

server:
  port: 8082

logging:
  level:
    ROOT: INFO
